CREATE SCHEMA IF NOT EXISTS currency_exchange;

CREATE TABLE IF NOT EXISTS currency_exchange.currency
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code      varchar(3),
    full_name varchar,
    sign      varchar
);

CREATE TABLE IF NOT EXISTS currency_exchange.exchange_rate
(
    id                 int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency_id   int REFERENCES currency_exchange.currency (id),
    target_currency_id int REFERENCES currency_exchange.currency (id),
    rate               decimal(6)
);

CREATE TABLE IF NOT EXISTS users
(
    id                         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                   VARCHAR(255) UNIQUE NOT NULL,
    email                      VARCHAR(255) UNIQUE NOT NULL,
    password                   VARCHAR(255)        NOT NULL,
    role                       VARCHAR(50)         NOT NULL,
    is_account_non_expired     BOOLEAN DEFAULT TRUE,
    is_account_non_locked      BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    is_enabled                 BOOLEAN DEFAULT TRUE
);
